spring.cloud.nacos.config.file-extension=yml

spring.cloud.nacos.config.server-addr=${NACOS_CONFIG_SERVER:maozi-cloud-nacos:8848}

spring.cloud.nacos.config.shared-dataids=cloud-nacos.yml,cloud-dubbo.yml,cloud-sentinel.yml,boot-monitor.yml,api-whitelist.yml,cloud-oauth.yml,boot-redis.yml,boot-swagger.yml,boot-lock.yml,boot-arthas.yml,cloud-default.yml