#!/bin/bash

# ============================================================
# maozi-cloud-monomer-service 专用部署脚本 (self-contained)
# (源码模块为 maozi-cloud-all-service, 容器 / 镜像名独立命名, 见下方配置)
# ------------------------------------------------------------
# 与标准 build 流程解耦:
#   - 配置内嵌在脚本顶部, 不写入 maozi-cloud-services.json
#   - 用专属的 maozi-cloud-monomer-docker/docker-compose.yml 拉起容器
#     (all-service 跟 gateway 都占 1000 端口, 与 services-docker 互斥,
#      不能同时跑; 因此单独建 compose, 不混在 services-docker 里)
#   - Dockerfile 在脚本里 heredoc 生成, 不依赖 maozi-cloud-service-image.template
# ------------------------------------------------------------
# 使用:
#   ./maozi-cloud-deploy-all-monomer.sh           # mvn 构建 + 部署
#   ./maozi-cloud-deploy-all-monomer.sh --no-build  # 跳过 mvn, 直接用已有 jar 部署
# ------------------------------------------------------------
# 前置:
#   1. maozi-cloud-basics-docker 已启动 (nacos / mysql / redis)
#   2. maozi-cloud-base-jdk:1.0.0 已构建 (由 maozi-cloud-deploy-all-distributed-force.sh 完成)
#   3. 外部网络 maozi-cloud-network 已创建
#   4. 如 services-docker 里的 gateway 在跑, 先停掉 (端口 1000 冲突):
#      docker-compose -f .../maozi-cloud-distributeds-docker/docker-compose.yml stop maozi-cloud-gateway-service
# ============================================================

cd "$(dirname "$0")"
current_directory="$(pwd)"
# 源码仓库根目录: 由脚本所在位置推导 (maozi-cloud-deploy-shell-run 向上四级);
# 当前结构下脚本位于 maozi-cloud-script/maozi-cloud-deploy 内, 源码仓库 maozi-cloud-parent 是 maozi-cloud-script 的同级目录,
# 向上四级无 pom.xml 时进入 maozi-cloud-parent (兼容脚本位于仓库内部的旧结构)
repo_candidate="$(cd "$current_directory/../../../.." && pwd)"
if [ -f "$repo_candidate/pom.xml" ]; then
	repo_root="$repo_candidate"
else
	repo_root="$repo_candidate/maozi-cloud-parent"
fi
cd "$repo_root"

# ============================================================
# 配置 (与 maozi-cloud-services.json defaults 保持一致, 方便维护)
# ============================================================
# SERVICE_NAME: 容器 / 镜像 / compose 服务名 (与 maozi-cloud-monomer-docker 对应)
# MODULE_NAME:  Maven artifactId, 决定源码模块目录与产物 jar 文件名,
#               两者独立维护, 改容器名无需动后端模块
SERVICE_NAME="maozi-cloud-monomer-service"
SERVICE_PORT=1000
MODULE_NAME="maozi-cloud-all-service"
MODULE_DIR="maozi-cloud-service/maozi-cloud-services/${MODULE_NAME}"
BASE_IMAGE="maozi-cloud-base-jdk:1.0.0"
# OTel=false: 用 base-jdk 即可, 不需要 business-jdk 里的 OTel agent
JVM_PARAMS="-Xms256m -Xmx256m -Xss256k -XX:MaxMetaspaceSize=192m -XX:+UseSerialGC -XX:CompressedClassSpaceSize=32m -XX:ReservedCodeCacheSize=32m -XX:MaxDirectMemorySize=32m"
IMAGE_TAG="${SERVICE_NAME}:laster"
# 部署用的 compose 文件 (端口 / 网络 / 日志挂载都在里面, 改部署参数改这里)
COMPOSE_FILE="$current_directory/../../maozi-cloud-deploy-docker/maozi-cloud-monomer-docker/docker-compose.yml"

# ============================================================
# 1. Maven 构建 (可选)
# ------------------------------------------------------------
# -am (also-make) 把 MODULE_DIR 的上游依赖模块也纳入 reactor 一起构建,
# 否则 maven 会把 oauth-business / system-business 等当外部依赖去仓库拉,
# 本地仓库缺失时就会因 HTTP blocker 失败 (或下载不必要的远程包).
# 注意: 标准 jar-utils.sh 用的是 -amd (also-make-dependents), 那是为增量
# 构建"改了 X, 重建 X 的下游"设计的; 部署单服务的场景方向相反, 用 -am.
# ============================================================
if [ "$1" != "--no-build" ]; then
    echo "[build] mvn clean install -pl $MODULE_DIR -am"
    mvn clean install -T 16C -Dmaven.compile.fork=true -Dmaven.test.skip=true \
        -pl "$MODULE_DIR" -am
    if [ $? -ne 0 ]; then
        echo "[build] FAILED: mvn error, abort"
        exit 1
    fi
fi

# ============================================================
# 2. 校验 jar 存在
# ============================================================
jar_path="$repo_root/$MODULE_DIR/target/${MODULE_NAME}.jar"
if [ ! -f "$jar_path" ]; then
    echo "[deploy] jar not found: $jar_path"
    echo "         run with no args to trigger mvn build, or check MODULE_DIR"
    exit 1
fi

# ============================================================
# 3. 准备临时构建目录, 拷贝 jar + 写 Dockerfile
# ============================================================
build_dir="$(mktemp -d -t "${SERVICE_NAME}-build")"
trap "rm -rf '$build_dir'" EXIT
# 拷贝时统一重命名为 SERVICE_NAME.jar, 让 Dockerfile 的 COPY / CMD 与容器内
# /application/${APPLICATION_NAME} 路径自洽 (jar 原名仍是 Maven artifactId)
cp "$jar_path" "$build_dir/${SERVICE_NAME}.jar"

# heredoc 里 ${VAR} 是 Dockerfile 运行时变量 (java 启动时才解析),
# \${VAR} 写到 Dockerfile 里就是 ${VAR} 字面量, 由 docker build 阶段保留,
# 运行时再解析. 这里全用 \${} 让 heredoc 不在脚本侧展开.
cat > "$build_dir/Dockerfile" <<EOF
# ============================================================
# Dockerfile — $SERVICE_NAME (AUTO-GENERATED by maozi-cloud-deploy-all-monomer.sh)
# ------------------------------------------------------------
# 聚合服务: 把所有业务模块打成一个 jar, 单端口 1000 暴露.
# OTel=false, 无 Dubbo, 基础镜像用 maozi-cloud-base-jdk (不带 OTel agent).
# ============================================================
FROM $BASE_IMAGE

ENV APPLICATION_NAME=$SERVICE_NAME
ENV APPLICATION_PORT=$SERVICE_PORT

RUN mkdir -p /application/\${APPLICATION_NAME}

WORKDIR /application/\${APPLICATION_NAME}

COPY ./${SERVICE_NAME}.jar ./

CMD java -server \\
  $JVM_PARAMS \\
  --add-opens java.base/java.math=ALL-UNNAMED \\
  --add-opens java.base/java.lang=ALL-UNNAMED \\
  --add-opens java.base/java.lang.reflect=ALL-UNNAMED \\
  -jar \${APPLICATION_NAME}.jar

EXPOSE \${APPLICATION_PORT}
EOF

# ============================================================
# 4. 构建 docker 镜像
# ============================================================
echo "[deploy] building image $IMAGE_TAG"
(cd "$build_dir" && docker buildx build -f Dockerfile -t "$IMAGE_TAG" .)
if [ $? -ne 0 ]; then
    echo "[deploy] FAILED: docker buildx error, abort"
    exit 1
fi

# ============================================================
# 5. docker-compose up -d (停旧 / 起新由 compose 自动处理)
# ------------------------------------------------------------
# 端口 / 网络 / 日志挂载 / 环境变量都在 COMPOSE_FILE 里声明, 改部署参数改那里.
# compose up -d 会自动重建基于新镜像的容器 (因为 image: maozi-cloud-monomer-service:laster)
# ============================================================
echo "[deploy] docker-compose -f $COMPOSE_FILE up -d"
docker-compose -f "$COMPOSE_FILE" up -d
if [ $? -ne 0 ]; then
    echo "[deploy] FAILED: docker-compose up error"
    exit 1
fi

echo "[deploy] done: $SERVICE_NAME -> $IMAGE_TAG (port $SERVICE_PORT)"
