spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          # http 或 rpc
#          mode: http
          # 客户端id
          client-id: system
          # 客户端秘钥
          client-secret: 123456