<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.maozi</groupId>
        <artifactId>maozi-cloud-business-ai</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>maozi-cloud-ai-api</artifactId>

    <properties>
        <spring-ai.version>1.0.0</spring-ai.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <!-- DTO 数据传输对象，定义接口出入参模型 -->
        <dependency>
            <groupId>com.maozi</groupId>
            <artifactId>maozi-cloud-domain-dto</artifactId>
            <version>${maozi-cloud-domain-dto.version}</version>
        </dependency>

        <!-- VO 视图对象，定义返回给前端的展示模型 -->
        <dependency>
            <groupId>com.maozi</groupId>
            <artifactId>maozi-cloud-domain-vo</artifactId>
            <version>${maozi-cloud-domain-vo.version}</version>
        </dependency>

        <!-- 基础枚举定义，如通用状态、类型枚举等 -->
        <dependency>
            <groupId>com.maozi</groupId>
            <artifactId>maozi-cloud-domain-enum</artifactId>
            <version>${maozi-cloud-domain-enum.version}</version>
        </dependency>

        <!-- 服务 API 基类，提供通用的服务接口定义和异常封装 -->
        <dependency>
            <groupId>com.maozi</groupId>
            <artifactId>maozi-cloud-service-api</artifactId>
            <version>${maozi-cloud-service-api.version}</version>
        </dependency>

        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
        </dependency>

    </dependencies>

</project>