{
 "title": "maozi-cloud-monitor",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut). Data from prometheus (which auto install by istio service-mesh on Kubernetes)",
 "tags": [ "manzi-cloud" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values({application=\"$application\"},environment)"
    }
   },
   {
    "name": "instances",
    "label": "instances",
    "query": {
     "query": "label_values({application=~\"$application\", environment=\"$environment\"},instances)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "存活时长",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}"
    }
   ]
  },
  {
   "title": "启动时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}*1000"
    }
   ]
  },
  {
   "title": "堆使用率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instances=\"$instances\",environment=\"$environment\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "非堆使用率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instances=\"$instances\",environment=\"$environment\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "CPU负载",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "线程数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "GC负载",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}[1m])) by (application, environment,instance) / on(application,environment, instance) system_cpu_count",
     "legendFormat": "live"
    }
   ]
  },
  {
   "title": "总内存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "堆内存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "非堆内存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "元数据区",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"Metaspace\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"Metaspace\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"Metaspace\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "压缩类空间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"Compressed Class Space\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"Compressed Class Space\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"Compressed Class Space\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "代码总缓存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeCache\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeCache\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeCache\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "非方法代码缓存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeHeap \\\\'non-nmethods\\\\'\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeHeap \\\\'non-nmethods\\\\'\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeHeap \\\\'non-nmethods\\\\'\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "带采样的代码缓存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeHeap \\\\'profiled nmethods\\\\'\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeHeap \\\\'profiled nmethods\\\\'\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeHeap \\\\'profiled nmethods\\\\'\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "不带采样的代码缓存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeHeap \\\\'non-profiled nmethods\\\\'\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeHeap \\\\'non-profiled nmethods\\\\'\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"CodeHeap \\\\'non-profiled nmethods\\\\'\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "GC STW平均耗时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "GC STW频率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "类加载字节数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "类释放字节数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{application=\"$application\",instances=\"$instances\",environment=\"$environment\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  {
   "title": "内存字节数分配",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instances=\"$instances\",environment=\"$environment\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "直接内存空间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"direct\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "jvm_buffer_count_buffers{application=\"$application\", instances=\"$instances\",environment=\"$environment\",id=~\"direct\"}",
     "legendFormat": "buffers"
    }
   ]
  }
 ]
}