{
 "title": "maozi-cloud-http",
 "tags": [ "manzi-cloud" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values({application=\"$application\"},environment)"
    }
   },
   {
    "name": "instances",
    "label": "instances",
    "query": {
     "query": "label_values({application=\"$application\", environment=\"$environment\"},instances)"
    }
   },
   { "name": "uri", "label": "uri", "query": ".*" },
   {
    "name": "filter",
    "label": "filter",
    "query": "/actuator/.*|/actuator|NOT_FOUND|UNKNOWN|REDIRECTION|/v3/api-docs"
   }
  ]
 },
 "panels": [
  {
   "title": "总请求数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri=~\"$uri\",uri!~\"$filter\",uri!=\"/**\"})"
    }
   ]
  },
  {
   "title": "总异常请求数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri!~\"$filter\",uri=~\"$uri\", outcome!=\"SUCCESS\",uri!=\"/**\"})"
    }
   ]
  },
  {
   "title": "接口请求数",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri=~\"$uri\",uri!~\"$filter\",uri!=\"/**\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "平均请求RT",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri=~\"$uri\",uri!~\"$filter\"}) / sum by(uri)(http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",uri=~\"$uri\",uri!~\"$filter\",uri!=\"/**\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "错误请求",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri=~\"$uri\",uri!~\"$filter\",uri!=\"/**\",status!~\"2.*|1.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "成功请求百分比",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri!~\"$filter\",uri=~\"$uri\",status=~\"2.*\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri!~\"$filter\",uri=~\"$uri\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "失败请求百分比",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri!~\"$filter\",uri=~\"$uri\",status!~\"2.*\",uri!=\"/**\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri=~\"$uri\",uri!~\"$filter\",uri!=\"/**\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "99%请求平均RT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri!~\"$filter\",uri=~\"$uri\",uri!=\"/**\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "95%请求平均RT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{application=\"$application\",environment=\"$environment\",instances=\"$instances\",uri!~\"$filter\",uri=~\"$uri\",uri!=\"/**\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "每秒请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",uri=~\"$uri\",instances=\"$instances\",uri!~\"$filter\",uri!=\"/**\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "正常日志",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{environment=\"$environment\",service=\"$application\"} | level =~ `INFO|DEBUG` | json | line_format \"[ {{.timestamp}} ]  [ Level：{{.level}} ]  [ TID：{{.trace_id}} ]  [ Service：{{.service}} ]  [ Environment：{{.environment}} ]  {{.message}}\""
    }
   ]
  },
  {
   "title": "异常日志",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{environment=\"$environment\",service=\"$application\"} | level =~ `ERROR|WARN|error` | json | line_format \"[ {{.timestamp}} ]  [ Level：{{.level}} ]  [ TID：{{.trace_id}} ]  [ Service：{{.service}} ]  [ Environment：{{.environment}} ]  {{.message}}\""
    }
   ]
  }
 ]
}